# Generated by Django 2.1.15 on 2021-05-22 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bodytext',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='permalink',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='update_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.date(2021, 5, 22)),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.time(23, 46, 21, 222406)),
        ),
        migrations.AddField(
            model_name='event',
            name='user_name',
            field=models.CharField(default='username', max_length=100, primary_key=True, serialize=False),
        ),
    ]
