# Generated by Django 2.1.15 on 2021-05-25 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210522_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_desc',
            field=models.TextField(default='desc', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.date(2021, 5, 25)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.time(23, 14, 49, 668453)),
        ),
    ]
