# Generated by Django 2.1.15 on 2021-07-29 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20210730_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='country_svg',
            field=models.FileField(default='file name', upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.time(2, 1, 32, 811077)),
        ),
    ]
