# Generated by Django 2.1.15 on 2021-08-04 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20210804_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.time(15, 8, 55, 185470)),
        ),
    ]
