# Generated by Django 2.1.15 on 2021-08-04 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20210804_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.time(18, 31, 53, 846618)),
        ),
    ]
