# Generated by Django 2.1.15 on 2021-08-06 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20210806_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.time(16, 31, 16, 48373)),
        ),
    ]
