# Generated by Django 2.1.15 on 2021-08-10 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20210811_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.time(2, 12, 1, 588908)),
        ),
        migrations.AlterField(
            model_name='maps',
            name='country_svg',
            field=models.TextField(max_length=1000),
        ),
    ]
